// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsLorV9ruEA4TABNxjLLcSgGZIr23YImc',
    appId: '1:620755611021:web:4bc1480fd6ed9e938d61c4',
    messagingSenderId: '620755611021',
    projectId: 'deneme-f46f9',
    authDomain: 'deneme-f46f9.firebaseapp.com',
    storageBucket: 'deneme-f46f9.firebasestorage.app',
    measurementId: 'G-EY2CG2E5G9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8N-05mBWRP9-O4UolUFGqFXG1T6kamxo',
    appId: '1:620755611021:android:ff5bca31cad1e19e8d61c4',
    messagingSenderId: '620755611021',
    projectId: 'deneme-f46f9',
    storageBucket: 'deneme-f46f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa64Qw80xWZPI95M_9_88gg__UXj7SEK0',
    appId: '1:620755611021:ios:53ce1dfbb09672e48d61c4',
    messagingSenderId: '620755611021',
    projectId: 'deneme-f46f9',
    storageBucket: 'deneme-f46f9.firebasestorage.app',
    iosBundleId: 'com.example.depremorganizasyonu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa64Qw80xWZPI95M_9_88gg__UXj7SEK0',
    appId: '1:620755611021:ios:53ce1dfbb09672e48d61c4',
    messagingSenderId: '620755611021',
    projectId: 'deneme-f46f9',
    storageBucket: 'deneme-f46f9.firebasestorage.app',
    iosBundleId: 'com.example.depremorganizasyonu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsLorV9ruEA4TABNxjLLcSgGZIr23YImc',
    appId: '1:620755611021:web:8e8a8ccaec7136768d61c4',
    messagingSenderId: '620755611021',
    projectId: 'deneme-f46f9',
    authDomain: 'deneme-f46f9.firebaseapp.com',
    storageBucket: 'deneme-f46f9.firebasestorage.app',
    measurementId: 'G-QJTVS240N0',
  );
}
